replicaCount: 1

image:
  repository: ghcr.io/nicosmuts/docker-pipeline-demo
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false

resources: {}

env:
  APP_ENV: "prod"
  LOG_LEVEL: "INFO"
  PAGE_SIZE: "10"
  PORT: "8080"