apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "books-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "books-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "books-api.name" . }}
    spec:
      containers:
        - name: books-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.env.PORT | int }}
          env:
            - name: APP_ENV
              value: "{{ .Values.env.APP_ENV }}"
            - name: LOG_LEVEL
              value: "{{ .Values.env.LOG_LEVEL }}"
            - name: PAGE_SIZE
              value: "{{ .Values.env.PAGE_SIZE }}"
            - name: PORT
              value: "{{ .Values.env.PORT }}"